import categoryMapJson from "./category-mapping.json";

/**
 * Maps freeform LLM-generated object_type values to standardized categories.
 * Source: flow-contents/docs/category_mapping_preview.json (~2,176 entries)
 * Generated by scripts/assign_categories.py
 */
export const CATEGORY_MAP: Record<string, string> = categoryMapJson;

/** The 22 standardized categories used across the pipeline */
export const STANDARDIZED_CATEGORIES = [
  "Furniture",
  "Home Decor",
  "Kitchen",
  "Clothing",
  "Footwear",
  "Accessories",
  "Jewelry",
  "Electronics",
  "Appliances (Large)",
  "Tools & Hardware",
  "Sports & Outdoors",
  "Toys, Games & Hobbies",
  "Books",
  "Media",
  "Office Supplies",
  "Linens & Textiles",
  "Health & Beauty",
  "Storage & Organization",
  "Lighting",
  "Garden & Patio",
  "Seasonal",
  "Pet Supplies",
  "Miscellaneous",
  "Excluded Property",
] as const;

/**
 * Maps BQ table IDs to their GCS room folder paths.
 * Some rooms have P2 (second-pass) folders that are merged into the same BQ table.
 */
export const ROOM_TABLE_MAP: Record<
  string,
  { displayName: string; gcsFolders: string[] }
> = {
  _01_master_bed_batch: {
    displayName: "01 Master Bed",
    gcsFolders: ["Palisair Photos/01 Master Bed"],
  },
  _02_master_bath_batch: {
    displayName: "02 Master Bath",
    gcsFolders: ["Palisair Photos/02 Master Bath"],
  },
  _03_office_batch: {
    displayName: "03 Office",
    gcsFolders: ["Palisair Photos/03 Office"],
  },
  _05_office_bath_batch: {
    displayName: "05 Office Bath",
    gcsFolders: ["Palisair Photos/05 Office Bath"],
  },
  _05_shared_bath_batch: {
    displayName: "05 Office Bath",
    gcsFolders: ["Palisair Photos/05 Office Bath"],
  },
  _06_living_room_batch: {
    displayName: "06 Living Room",
    gcsFolders: [
      "Palisair Photos/06 Living Room",
      "Palisair Photos/Living Room P2",
    ],
  },
  _07_coat_closet_batch: {
    displayName: "07 Coat Closet",
    gcsFolders: ["Palisair Photos/07 Coat Closet"],
  },
  _08_entry_bathroom_batch: {
    displayName: "08 Entry Bathroom",
    gcsFolders: ["Palisair Photos/08 Entry Bathroom"],
  },
  _09_den_batch: {
    displayName: "09 Den",
    gcsFolders: ["Palisair Photos/09 Den", "Palisair Photos/Den P2"],
  },
  _10_kitchen_batch: {
    displayName: "10 Kitchen",
    gcsFolders: ["Palisair Photos/10 Kitchen", "Palisair Photos/Kitchen P2"],
  },
  _11_garage_batch: {
    displayName: "11 Garage",
    gcsFolders: [
      "Palisair Photos/11 Garage",
      "Palisair Photos/11 Garage overview ",
      "Palisair Photos/Garage P2",
    ],
  },
  _12_laundry_room_batch: {
    displayName: "12 Laundry Room",
    gcsFolders: ["Palisair Photos/12 Laundry room"],
  },
  _13_outside_items_batch: {
    displayName: "13 Outside Items",
    gcsFolders: ["Palisair Photos/13 Outside items"],
  },
  hallway_batch: {
    displayName: "Hallway",
    gcsFolders: ["Palisair Photos/Hallway"],
  },
  will_office_batch: {
    displayName: "Will's Office",
    gcsFolders: ["Palisair Photos/Will Office"],
  },
};

/** Map an object_type to a standardized category, defaulting to "Miscellaneous" */
export function mapCategory(objectType: string | null | undefined): string {
  if (!objectType) return "Miscellaneous";
  return CATEGORY_MAP[objectType] ?? "Miscellaneous";
}

/**
 * Compute audit_status from the 3-layer priority mapping.
 *
 * Layer 1: Human override (review_action) — trumps everything
 * Layer 2: Pipeline status — trumps vision match
 * Layer 3: Vision match — only matters if status = 'final item'
 */
export function computeAuditStatus(
  reviewAction: string | null | undefined,
  pipelineStatus: string | null | undefined,
  visualMatch: string | null | undefined
): "final" | "needs_review" | "duplicate" | "wrong" {
  // Layer 1: Human override
  if (reviewAction) {
    const ra = reviewAction.toLowerCase().trim();
    if (ra === "final" || ra === "price high") return "final";
    if (ra === "duplicate") return "duplicate";
    if (ra === "wrong detection" || ra === "wrong product") return "wrong";
    // client review, RE-RUN, rerun, or anything else
    return "needs_review";
  }

  // Layer 2: Pipeline status
  if (pipelineStatus) {
    const ps = pipelineStatus.toLowerCase().trim();
    if (ps === "wrong item") return "wrong";
    if (ps.startsWith("duplicate of")) return "duplicate";
    if (ps === "human review") return "needs_review";
    // 'final item' falls through to Layer 3
    if (ps !== "final item") return "needs_review";
  }

  // Layer 3: Vision match (reached when pipeline status = 'final item' or null)
  if (visualMatch) {
    const vm = visualMatch.toLowerCase().trim();
    if (vm === "match") return "final";
  }

  return "needs_review";
}
